plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.shamela.apptheme'
    compileSdk versions.androidCompileSdk

    defaultConfig {
        minSdk versions.androidMinSdk
        targetSdk versions.androidTargetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}
dependencies {
    implementation "androidx.core:core-ktx:$versions.core_ktx"
    implementation platform("org.jetbrains.kotlin:kotlin-bom:$versions.kotlin_bom")
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$versions.lifecycle_runtime_ktx"
    implementation "androidx.activity:activity-compose:$versions.compose_activity"

    implementation platform("androidx.compose:compose-bom:$versions.compose_bom")
    implementation("androidx.compose.animation:animation-core")
    implementation("androidx.compose.animation:animation")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.ui:ui-geometry")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.foundation:foundation-layout")
    implementation("androidx.compose.runtime:runtime-livedata")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material")
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.compose.runtime:runtime-rxjava2")
    implementation("androidx.compose.ui:ui-text")
    implementation("androidx.compose.ui:ui-util")
    implementation("androidx.compose.ui:ui-viewbinding")
    implementation("androidx.compose.ui:ui-tooling")


    //-> WorkManager
    implementation "androidx.work:work-runtime-ktx:$versions.workmanager"
    //-> Jsoup Parser
    implementation 'org.jsoup:jsoup:1.15.3'
    //-> SQLite support library
    api 'com.github.requery:sqlite-android:3.42.0'
    // R2 modules
    implementation("com.github.codetoart:r2-shared-kotlin:$versions.r2SharedKotlin") {
        exclude group: 'com.github.kittinunf.fuel', module: 'fuel'
        exclude group: 'com.github.kittinunf.fuel', module: 'fuel-android'
        changing = true
    }
    implementation("com.github.codetoart:r2-streamer-kotlin:$versions.r2StreamerKotlin") {
        exclude group: "org.slf4j", module: "slf4j-api"
        exclude group: 'com.github.kittinunf.fuel', module: 'fuel'
        exclude group: 'com.github.kittinunf.fuel', module: 'fuel-android'
        changing = true
    }

    implementation 'com.github.kittinunf.fuel:fuel:2.3.1'
    implementation 'com.github.kittinunf.fuel:fuel-android:2.3.1'

    //-> Compose Navigation
    implementation "androidx.navigation:navigation-compose:$versions.navigation_compose"

    //->Kotlin Reflection
    implementation "org.jetbrains.kotlin:kotlin-reflect:2.1.0"

    //-> Testing
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
}